### PR TITLE
improve local ice candidate gathering

### PR DESCRIPTION
**Pull request by koush**
gather all network addresses, and not just the first.
sort the interfaces similar to chrome, and don't simply use the
order it is returned.

### CODE REVIEW

**Comment by koush** [comment]
The underlying issue was that werift only sends the first local candidate as returned from nom's ip.address(). In my case, that's my wifi adapter, and not my ethernet adapter. I believe that's bug in the library. In any case, werift should send all local candidates.

I compared what chrome sends versus what werift sends to achieve parity:

Chrome:

```
candidate:2328317101 1 tcp 1518280447 172.16.173.1 9 typ host tcptype active generation 0 ufrag rWda network-id 1
candidate:1375685859 1 tcp 1518214911 192.168.242.1 9 typ host tcptype active generation 0 ufrag rWda network-id 2
candidate:647890050 1 tcp 1518149375 192.168.2.157 9 typ host tcptype active generation 0 ufrag rWda network-id 3
candidate:3495337529 1 tcp 1518083839 192.168.2.206 9 typ host tcptype active generation 0 ufrag rWda network-id 4 network-cost 10
candidate:2328317101 1 tcp 1518280447 172.16.173.1 9 typ host tcptype active generation 0 ufrag rWda network-id 1
candidate:1375685859 1 tcp 1518214911 192.168.242.1 9 typ host tcptype active generation 0 ufrag rWda network-id 2
candidate:647890050 1 tcp 1518149375 192.168.2.157 9 typ host tcptype active generation 0 ufrag rWda network-id 3
candidate:3495337529 1 tcp 1518083839 192.168.2.206 9 typ host tcptype active generation 0 ufrag rWda network-id 4 network-cost 10
```

Werift:

```
a=candidate:c24e75aad7652fe357c8506e8 1 udp 2130706431 172.16.173.1 65322 typ host
a=candidate:7935dda87b0b68576c4c9658c 1 udp 2130706431 192.168.242.1 55181 typ host
a=candidate:621fb5f52ec6d29703e83c789 1 udp 2130706431 192.168.2.157 59503 typ host
a=candidate:de76ba31eec6d6710ac4c0a7c 1 udp 2130706431 192.168.2.206 65055 typ host
a=candidate:3477b8750b805f3f17cba7af3 1 udp 2130706431 fe80::781e:51ff:fe2f:eb4d 63553 typ host
a=candidate:49652e57f52bff97f0a007315 1 udp 2130706431 fe80::18c0:4dff:fe20:c564 50077 typ host
a=candidate:20bcca003a23f4cf5326812a5 1 udp 2130706431 fe80::18c0:4dff:fe20:c565 60990 typ host
a=candidate:355c64d19ee707276e872f797 1 udp 2130706431 fe80::d5:a427:3ebe:407f 65240 typ host
a=candidate:f9652a535387b150722fbfcd8 1 udp 2130706431 fe80::1403:7962:cf81:faf6 55856 typ host
a=candidate:3477b8750b805f3f17cba7af3 1 udp 2130706431 fe80::781e:51ff:fe2f:eb4d 63039 typ host
```

Here is my os.networkInterfaces, for reference:

```json
{
  lo0: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    },
    {
      address: '::1',
      netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '::1/128',
      scopeid: 0
    },
    {
      address: 'fe80::1',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: 'fe80::1/64',
      scopeid: 1
    }
  ],
  en5: [
    {
      address: 'fe80::1403:7962:cf81:faf6',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: 'd0:03:4b:cf:67:29',
      internal: false,
      cidr: 'fe80::1403:7962:cf81:faf6/64',
      scopeid: 8
    },
    {
      address: '192.168.2.206',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: 'd0:03:4b:cf:67:29',
      internal: false,
      cidr: '192.168.2.206/24'
    }
  ],
  en1: [
    {
      address: 'fe80::d5:a427:3ebe:407f',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '18:c0:4d:02:dc:06',
      internal: false,
      cidr: 'fe80::d5:a427:3ebe:407f/64',
      scopeid: 9
    },
    {
      address: '192.168.2.157',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '18:c0:4d:02:dc:06',
      internal: false,
      cidr: '192.168.2.157/24'
    }
  ],
  awdl0: [
    {
      address: 'fe80::781e:51ff:fe2f:eb4d',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '7a:1e:51:2f:eb:4d',
      internal: false,
      cidr: 'fe80::781e:51ff:fe2f:eb4d/64',
      scopeid: 11
    }
  ],
  llw0: [
    {
      address: 'fe80::781e:51ff:fe2f:eb4d',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '7a:1e:51:2f:eb:4d',
      internal: false,
      cidr: 'fe80::781e:51ff:fe2f:eb4d/64',
      scopeid: 12
    }
  ],
  utun0: [
    {
      address: 'fe80::3fb8:6b18:d47c:6e95',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::3fb8:6b18:d47c:6e95/64',
      scopeid: 13
    }
  ],
  utun1: [
    {
      address: 'fe80::fd5e:aa3f:95d8:6c42',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::fd5e:aa3f:95d8:6c42/64',
      scopeid: 14
    }
  ],
  utun2: [
    {
      address: 'fe80::ce81:b1c:bd2c:69e',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::ce81:b1c:bd2c:69e/64',
      scopeid: 15
    }
  ],
  utun3: [
    {
      address: 'fe80::8670:46a3:73bb:ffab',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::8670:46a3:73bb:ffab/64',
      scopeid: 16
    }
  ],
  utun4: [
    {
      address: 'fe80::d47a:94ae:5812:7d93',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::d47a:94ae:5812:7d93/64',
      scopeid: 17
    }
  ],
  utun5: [
    {
      address: 'fe80::76b9:199d:59e0:4eee',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::76b9:199d:59e0:4eee/64',
      scopeid: 18
    }
  ],
  utun6: [
    {
      address: 'fe80::ebb5:e867:4552:74a6',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::ebb5:e867:4552:74a6/64',
      scopeid: 19
    }
  ],
  utun7: [
    {
      address: 'fe80::ccc9:af5b:c1af:20bd',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::ccc9:af5b:c1af:20bd/64',
      scopeid: 29
    }
  ],
  utun8: [
    {
      address: 'fe80::4bda:4dcb:b25a:9192',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: false,
      cidr: 'fe80::4bda:4dcb:b25a:9192/64',
      scopeid: 30
    }
  ],
  bridge100: [
    {
      address: '172.16.173.1',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '1a:c0:4d:20:c5:64',
      internal: false,
      cidr: '172.16.173.1/24'
    },
    {
      address: 'fe80::18c0:4dff:fe20:c564',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '1a:c0:4d:20:c5:64',
      internal: false,
      cidr: 'fe80::18c0:4dff:fe20:c564/64',
      scopeid: 21
    }
  ],
  bridge101: [
    {
      address: '192.168.242.1',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: '1a:c0:4d:20:c5:65',
      internal: false,
      cidr: '192.168.242.1/24'
    },
    {
      address: 'fe80::18c0:4dff:fe20:c565',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: '1a:c0:4d:20:c5:65',
      internal: false,
      cidr: 'fe80::18c0:4dff:fe20:c565/64',
      scopeid: 23
    }
  ]
}
```

**Comment by koush** [comment]
Unfortunately I can't seem to figure out a way to determine if a network address is wired or wireless. That would allow using the `network-cost 10` hint.

**Comment by shinyoshiaki** [comment]
I will review later

**Comment by shinyoshiaki** [comment]
Since the communication involves pairs that never communicate, it will take too much time if the number of retransmissions of the request is not limited when doing the Terminology Check.

**Comment by shinyoshiaki** [comment]
If put 4 in the 4th argument of pair.protocol.request, you can eliminate candidates that do not respond within 800ms, so it would be a good idea to do so
https://github.com/shinyoshiaki/werift-webrtc/blob/develop/packages/ice/src/ice.ts#L706

**Pull request merged**
