### PR TITLE
renegotiation should reset the sequence numbers to 0

### PR DESCRIPTION
**Pull request by koush**
https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.2

fixes https://github.com/shinyoshiaki/werift-webrtc/issues/254

### CODE REVIEW

**Comment by koush** [comment]
This fixes my bug. But I get the feeling this is not the correct way to do it. Maybe the sequence numbers should always be reset at the start of flight 2? The rfc indicates it MUST start with client 0 and server 1.

**Comment by koush** [comment]
I think this is likely correct github.com:koush/werift-webrtc

**Comment by shinyoshiaki** [comment]
> I think this is likely correct the fix in retrospect https://github.com/shinyoshiaki/werift-webrtc/commit/4b55033c01ec1bf98043d3c35c5c238650779a85

The renegotiation of dtls in werift is a dummy implementation, so I'd like to adopt this change

**Comment by koush** [comment]
> > I think this is likely correct the fix in retrospect [4b55033](https://github.com/shinyoshiaki/werift-webrtc/commit/4b55033c01ec1bf98043d3c35c5c238650779a85)
> 
> The renegotiation of dtls in werift is a dummy implementation, so I'd like to adopt this change Please Change your PR.

Done.

**Comment by koush** [comment]
Actually, reading closer, the record sequence number should not be changed. Let me test and modify.

> Note, however, that from the perspective of the DTLS record layer,
>   the retransmission is a new record.  This record will have a new
>   DTLSPlaintext.sequence_number value.

**Comment by koush** [comment]
Despite what the RTC says, it seems that both need to be reset to zero for the fix to work. The change is functionally correct.

**Pull request merged**
