### PR TITLE
bundlePolicy

### PR DESCRIPTION
**Pull request by shinyoshiaki**

### CODE REVIEW

**Comment by shinyoshiaki** [comment]
@koush 

When you are free, could you please make sure that this version works fine in your project?

`v0.15.0-alpha.1`

**Comment by koush** [comment]
Does not work unfortunately, both bundle and non bundle are failing for me on this branch. I'll bisect and find the issue sometime this week if possible.

**Comment by koush** [comment]
Does not work unfortunately, both bundle and non bundle are failing for me on this branch. I'll bisect and find the issue sometime this week if possible.

**Comment by koush** [comment]
Regression caused by 9eb323d0220935f3ef247eebd1567f831c72f156.

**Comment by koush** [comment]
I'll check. If I recall, I think it just failed to get into a connected state.

**Comment by dgreif** [comment]
@koush do you mind following up here?  I'd love to get all the bundle changes finished up and into the main-line release.  Now that I have more users on werift, I'm seeing a fair number just fail to get fully connected.  In particular, it seems to get to `iceConnectionState: connected` but `connectionState` is stuck at `connecting`. 🤞 that some of the changes since your fork will fix the issues.

**Comment by koush** [comment]
I did not see any errors but I didn't look too closely. I provided the commit that broke my change.

**Comment by koush** [comment]
fixed with https://github.com/shinyoshiaki/werift-webrtc/pull/202

**Comment by shinyoshiaki** [comment]
I'll check tomorrow

**Comment by shinyoshiaki** [comment]
@koush @dgreif 
released at v0.15.0

**Pull request merged**
